export const products = [
    { id: 1, title: 'Voice Solutions', description: 'Voice solution is an integral part of business communication. By offering a simple means for everyone to get in touch with a business, voice services have always been crucial to improving communication and business connections. We provide in-house communication facilities regardless of location or device to increase efficiency of your voice services.'},
    { id: 2, title: 'Security Solutions', description: 'Reduce your network risks with our modern solutions. Safeguard the crucial aspects of your business by defending against any threats. Fight unexpected stupefaction with security resilience. Ensure secure access from anywhere using our products.'},
    { id: 3, title: 'Surveillance Solutions', description: 'Security measures for your house or place of business must include surveillance systems. These systems can range from sophisticated alarm systems to wireless home security cameras. The appropriate tools can provide essential security according to your requirements.'},
    { id: 4, title: 'Access Control System', description: 'From card access to the newest biometrics, including fingerprint, smart card technology, and mobile credentials, access control is the foundation of efficient security controls. ThoughtsPro concocts solutions that will satisfy your demands now and expand with you in the future. Utilize our Services to maintain your access control system’s original performance and get the most out of your investment.'},
    { id: 5, title: 'Video Conferencing System', description: 'Our solutions include a whole ecosystem of hardware, software and services for video conferencing. Our team works wherever and however they want by enabling a quintessential hybrid conference experience, from home offices to boardrooms.'},
    { id: 6, title: 'Entrance Control Systems', description: 'We offer efficient and effective entrance control systems for controlling traffic and vehicle control with an expansive range of EC systems. It includes pedestrian entrance control, automated parking control systems and parking locks. We design it according to different circumstances and verticals.'},
    { id: 7, title: 'Real-Time Location Systems', description: 'With particular applications like staff tracking and high-value asset tracking, RTLS (Real-time location system) is utilized in many areas. RTLS has a prominent place in the healthcare sector as it can reliably6 locate, track, and handle assets, stock, or people.'},
    { id: 8, title: 'Data Center', description: 'A data center is a structure that consolidates an organization’s shared IT operations and pieces of equipment. Data centers are mainly used for storing, processing, and transferring data and applications.'},
    { id: 9, title: 'PA/VA Systems', description: 'Neotronics is specialized in designing, developing and providing public address and voice alarm (PA/VA) systems. We maintain the highest standards at all times from installation to maintenance.'},
];